package com.iknowhow.mhte.projectsexperience.exception;

public enum MhteProjectErrorMessage {
	PROJECT_NOT_FOUND,
	PROJECT_CONTRACTOR_NOT_FOUND,
	PROJECT_SUBCONTRACTOR_NOT_FOUND,
	CONSTRAINT_VALIDATION_ERROR,
	ALREADY_ASSIGNED,
	TOTAL_PERCENTAGE_EXCEEDS_MAX,
	CONTRACT_NOT_FOUND,
	ADAM_ALREADY_EXISTS,
	PROTOCOL_NUMBER_ALREADY_EXISTS,
	VALUES_CANNOT_BE_NEGATIVE,
	FILE_CANNOT_BE_UPLOADED,
	FILENET_FOLDER_ERROR
}
