package com.iknowhow.mhte.projectsexperience.exception;

public enum MhteProjectErrorMessage {
	PROJECT_NOT_FOUND,
	PROJECT_CONTRACTOR_NOT_FOUND,
	PROJECT_SUBCONTRACTOR_NOT_FOUND,
	CONSTRAINT_VALIDATION_ERROR,
	ALREADY_ASSIGNED,
	CONTRACT_NOT_FOUND,
	ADAM_ALREADY_EXISTS,
	PROTOCOL_NUMBER_ALREADY_EXISTS
}
